#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www/html
#Create a custom index.html file
echo "Hello World!" > /var/www/html/index/html

#Change the default configuration to serve the custom index.html
cat > /etc/nginx/sites-available/default << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL
service nginx start
