#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server, ensuring it is listening on port 80 and serves a page with "Hello World!" at the root.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo chown -R ubuntu /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
